--create the department table if it doesnt exists
CREATE TABLE IF NOT EXISTS DEPARTMENT(
    EMPLOYEE_ID TEXT,
    NAME TEXT,
    DEPARTMENT_ID TEXT,
    MANAGER_ID TEXT,
    SALARY REAL
);
--INSERT SIMPLE DATA INTO THE DEPARTMENT TABLE
INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES
('100','STEVEN KING','90','100',24000),
('101','NEENA KOCHCAR','90','100',17000),
('102','LEX DEHAAN','90','102',9000),
(