--create table if it does not EXISTS
CREATE TABLE IF NOT EXISTS NOBEL_WINZ(
    YEAR INTEGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

--INSERT SAMPLE DATA INTO THE NOBEL_WIN TABLE
INSERT INTO NOBEL_WINZ(YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY)VALUES
(1970, 'PHYSICS','HANNES ALFVEN','SWEDWN','SCIENTIST'),
(1970, 'PHYSICS','LOUIS NEEL', 'FRANCE','SCIENTIST'),
(1971,'PHYSICS','PAUL','FRANCE','SCIENTISTS'),
(1971,'CHEMISTRY','HAMILTON','SWEDEN','LINGUIST'), 
(1972,'LITERATURE','BERNARD KELSON','GERMANY','ECONOMIST'),
(1972,'ENCONOMICS','JOSEPH','RUSSIA','ECONOMISTS'),
(1973,'BIOLOGY','PHILIPS','MARTIN','USA'),
(1981,'PHYSIOLOGY','HANNAH','HUNARY','SCIENTISTS'),
(1975,'PHYSICS','PETER','CHILE','SCIENTISTS');

--select all records from the nobel_win table where the subject doesnt start with 'p'. 
SELECT*
FROM NOBEL_WINZ
WHERE SUBJECT NOT LIKE'P%';
