file_read = open('codingal2.txt','r')
print("File in Read Mode-")
print(file_read.read())
file_read.close()
file_write = open('codingal2.txt','w')
file_write.write("new content a")
file_write.write("new content b")
file_write.close()
file_append=open('codingal2.txt','a')
file_append.write("\n File in append mode....")
file_append.write("i am a codingal student and i am doing the python course rightnow")
file_append.close()
