CREATE TABLE IF NOT EXISTS STUDENTS(
    ROLE_NUMBER TEXT,
    STUDENT_NAME TEXT,
    MARKS_GOTTEN REAL
    );
--INSERT DATABASE
INSERT INTO STUDENTS(ROLE_NUMBER,STUDENT_NAME,MARKS_GOTTEN)VALUES
('4','ZAID',56.0),
('5','RAYAN',70.0),
('6','HUSSIEN',60.0);

SELECT AVG(MARKS_GOTTEN) AS Average_of_marks
FROM STUDENTS;

    